### ISSUE TITLE
Can we use dep?

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/ci-operator#108]
Or is it still impossible to vendor OpenShift client libraries with dep?

/cc @smarterclayton @deads2k

**Comment by deads2k** [comment]
@sttts indicated that it is possible, but there are sharp edges.  Is glide causing maintenance trouble?

**Comment by stevekuznetsov** [comment]
The "update everything all at once" approach of `glide` was surprising. @droslean can give more context

**Comment by droslean** [comment]
It seems that while we are trying to include one more package in our vendors, glide is trying to fetch all the updates. And since we don't have a stable versioning way in how we should get our vendors, everything falls apart. 

We should investigate exactly which commit tree we want to use for all our vendors in order to avoid this problem, or we should change to dep. Related [issue](https://github.com/Masterminds/glide/issues/328) in glide's repository.

**But even if we move to dep, we will have the same problem. We can't use the latest release of our vendors because that is breaking the code.**

So we still need to decide with commit tree we should use. And in that case, we don't need to change to dep, since we can already do it with glide.

**Comment by gabemontero** [comment]
also note that vendoring in openshift/client-go will not work out of the box with `dep`

Haseed noted a workaround in the `[aos-devel] glide vs dep? (was: operator-sdk and bringing in github.com/openshift/client-go as a dependency)` email thread of importing the versioned subpackage, if that is palpable to you.  

There were also some claims of issues with transitive dependencies with `dep` in that email thread, which I think I may have also seen when trying to vendor in both the operator sdk and openshift/client-go.

**Comment by stevekuznetsov** [comment]
@droslean we don't have that issue with `dep`, I successfully version-pin stuff and update a single dep all the time. _required_ transitive dep bumps are unavoidable and expected

**Comment by stevekuznetsov** [comment]
Looks like we can't use `dep` anyway
/close
