### ISSUE TITLE
Failures to delete already-deleted artifacts containers

### ISSUE THREAD

**Issue by wking** [openshift/ci-operator#228]
From [here][1]:

```
2018/12/05 14:37:13 error: unable to signal to artifacts container to terminate in pod release-latest, triggering deletion: could not run remote command: unable to upgrade connection: container not found ("artifacts")
2018/12/05 14:37:18 Ran for 45m45s
error: could not run steps: failed to wait for release pod to complete: could not wait for pod completion: pod release-latest was already deleted
```

This is similar to #197 / #198, where the same code-path was leading to a panic.  We no longer panic, but now we're apparently exiting with an error.  Ideally `ci-operator`'s response to "I'm trying to delete $CONTAINER and it's already gone" would change from "so I'm going to die" to "so great!  Moving on..." ;).

[1]: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/21611/pull-ci-openshift-origin-master-images/1339/build-log.txt

**Comment by droslean** [comment]
This is not related to #197 / #198.  That smells like a race condition in while deleting the pod.

**Comment by wking** [comment]
Cross-linking [rhbz#1693865][1].

[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1693865

**Comment by stevekuznetsov** [comment]
I think some of these are the artifacts container being part of an evicted pod -- we need to be best-effort in this case _anyway_ but it was the same root cause

**Comment by petr-muller** [comment]
There's a detailed analysis in the associated [BZ](https://bugzilla.redhat.com/show_bug.cgi?id=1693865#c12). TL;DR there's a read/deletion race when multiple ci-operator instances wait on a single pod to finish and try to collect artifacts from it. [PR](https://github.com/openshift/ci-operator/pull/348) should reduce occurrences in practice, but the race is still present.

These races are one thing and we should avoid them if possible, but ci-operator is currently not robust to handle third-parties deleting its workloads on the cluster.

**Comment by petr-muller** [comment]
https://github.com/openshift/ci-operator/pull/348 is a band-aid that should reduce occurrences of the race to minimum. We saw last occurrence before merge (May 20 2019 23:15:55 CEST) and none since, so the band-aid helped (we used to have 5-10 hits each day).
https://github.com/openshift/ci-operator/pull/351 improved the message for these situations (not just the race, but any event when pod is deleted under ci-operator's hand). Instead of:
```
error: could not run steps: release "release-latest" failed: pod release-latest was already deleted
```
this would be the output:
```
error: could not wait for pod 'release-latest': it is no longer present on the cluster (usually a result of a race or resource pressure. re-running the job should help)
error: pod was deleted while ci-operator step was waiting for it
```
For "proper" architectural fixes, two JIRAs were created:

- [Fix the race where artifacts pod may terminate while other ci-operators still need it](https://jira.coreos.com/browse/DPTP-411) 
- [Make ci-operator PodStep more resilient to pod deletions](https://jira.coreos.com/browse/DPTP-412)

We are monitoring the hits in Sentry and will prioritize these JIRAs accordingly.

Because the issue should not longer happen often enough to hamper CI service efficiency and the message is no longer confusing, closing.

/close
