### ISSUE TITLE
Rename `test_base_image` to something more intuitive

### ISSUE THREAD

**Issue by kargakis** [openshift/ci-operator#55]
`test_base_image` feels like the base image that is going to be used for running tests. Seems to be something different (the base image used for the binary builds). 

@stevekuznetsov @smarterclayton

**Comment by petr-muller** [comment]
The thing is that can be *also* a base for running tests - you can have a `tests` item that has `"from": "src"` running something like `make test-unit`, relying on make doing the binary build basically just as an implementation detail of the test.

**Comment by smarterclayton** [comment]
Agree - it’s the compilation or code or tooling image.

On Jul 24, 2018, at 5:39 AM, Michalis Kargakis <notifications@github.com>
wrote:

test_base_image feels like the base image that is going to be used for
running tests. Seems to be something different (the base image used for the
binary builds).

@stevekuznetsov <https://github.com/stevekuznetsov> @smarterclayton
<https://github.com/smarterclayton>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/ci-operator/issues/55>, or mute the thread

**Comment by smarterclayton** [comment]
It needs to be broader than test.  It should convey to the user that this
image is "source code + tooling needed to work with that source".  In s2i
or docker that's a base image.  It's also known as a builder image.  In RPM
this might be called the build root or build environment.  It might also be
called the build toolchain.

**Comment by stevekuznetsov** [comment]
Will be fixed with the migration to https://jira.coreos.com/browse/DPTP-95
/close
